import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/shared/components/header/header";
import styles from "./layout.module.scss";
import { QueryProvider } from "@/shared/providers/queryProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <QueryProvider>
                    <div className={styles.app}>
                        <div className={styles.page}>
                            <Header />
                            <div className={styles.main}>
                                {children}
                            </div>
                            <div className={styles.footer}>
                                © Copyrigth
                            </div>
                        </div>
                    </div>
                </QueryProvider>
            </body>
        </html>
    );
}
