import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/shared/components/header/header";
import styles from "./layout.module.scss";
import { QueryProvider } from "@/shared/providers/queryProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <QueryProvider>
                    <div className={styles.app}>
                        <div className={styles.page}>
                            <Header />
                            <div className={styles.main}>
                                {children}
                            </div>
                            <div className={styles.footer}>
                                © Copyrigth
                            </div>
                        </div>
                    </div>
                </QueryProvider>
            </body>
        </html>
    );
}
